POST http://localhost:3000/ride/create-ride
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDJlMDNmNDRmYWFkZjJiZDU2MTYxZSIsImlhdCI6MTc3ODczNTAyMSwiZXhwIjoxNzc4ODIxNDIxfQ.a8HgiRdbR8XcTR1UIn5lTvHEqeUAQFO-TaSftrrhh3I

{
  "pickup": "Kathmandu",
  "destination": "Butwal"
}

####
POST http://localhost:3000/ride/create-ride
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDJmMmE0NzdiZTVkYzllOTVhOTc3MSIsImlhdCI6MTc3ODczNzU1OSwiZXhwIjoxNzc4ODIzOTU5fQ.z9c-5LWWaEP4cLb_pUY5MMuGbXhNO--MGEkpIKvHalU

{
  "pickup": "Kathmandu",
  "destination": "jhapa"
}



